parameters:
    mailer_user: "airidasams@gmail.com"
    sender_name: "SymfonyHomeWork #3"

framework:
    translator: ~
    templating:
            engines: ['twig', 'php']

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: App\Entity\User
    from_email:
        address: "%mailer_user%"
        sender_name: "%mailer_user%"

    registration:
        form:
            type: App\Form\Type\FOSRegistrationFormType

twig:
  form_themes: ['bootstrap_4_horizontal_layout.html.twig']